version: "3.8"
services:
  go-server-base:
    container_name: "go-server-base"
    build:
      context: .
      target: base
      args:
        PORT: 8888
    ports:
      - "8888:8888"
    volumes:
      - .:/go/app/base
    command: "air"

  go-server-builder:
    container_name: "go-server-builder"
    build:
      context: .
      target: builder
      args:
        PORT: 8888
    ports:
      - "8889:8888"
    command: "./main"

  go-server-prod:
    container_name: "go-server-prod"
    build:
      context: .
      target: production
      args:
        PORT: 8888
    ports:
      - "8890:8888"
    command: "./main"

#  db:
#    container_name: "db"
#    image: postgres:14
#    restart: always
#    tty: true
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres:/data/postgres
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres